// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using medica1.Context;

#nullable disable

namespace medica1.Migrations
{
    [DbContext(typeof(MVCContext))]
    partial class MVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CombinationGeneric_Name", b =>
                {
                    b.Property<int>("Combinationgeneric_NamesID")
                        .HasColumnType("int");

                    b.Property<string>("GenericcombinationsMedicine_Type")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Combinationgeneric_NamesID", "GenericcombinationsMedicine_Type");

                    b.HasIndex("GenericcombinationsMedicine_Type");

                    b.ToTable("CombinationGeneric_Name");
                });

            modelBuilder.Entity("CombinationMedicine_Type", b =>
                {
                    b.Property<int>("CombinationMedicine_TypeID")
                        .HasColumnType("int");

                    b.Property<string>("Medicine_TypeCombinationMedicine_Type")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CombinationMedicine_TypeID", "Medicine_TypeCombinationMedicine_Type");

                    b.HasIndex("Medicine_TypeCombinationMedicine_Type");

                    b.ToTable("CombinationMedicine_Type");
                });

            modelBuilder.Entity("Generic_NameMedicine_Name", b =>
                {
                    b.Property<int>("Genetic_Namemedicine_NamesID")
                        .HasColumnType("int");

                    b.Property<int>("Medicine_Namegeneric_NamesID")
                        .HasColumnType("int");

                    b.HasKey("Genetic_Namemedicine_NamesID", "Medicine_Namegeneric_NamesID");

                    b.HasIndex("Medicine_Namegeneric_NamesID");

                    b.ToTable("Generic_NameMedicine_Name");
                });

            modelBuilder.Entity("medica1.Models.Combination", b =>
                {
                    b.Property<string>("Medicine_Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Create_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Max_Dose")
                        .HasColumnType("int");

                    b.Property<string>("Minimum_Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Streanth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Medicine_Type");

                    b.ToTable("combinations");
                });

            modelBuilder.Entity("medica1.Models.Generic_Name", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Change_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Short_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Generic_Names");
                });

            modelBuilder.Entity("medica1.Models.Medicine_Name", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medicine_Names");
                });

            modelBuilder.Entity("medica1.Models.Medicine_Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medicine_Types");
                });

            modelBuilder.Entity("CombinationGeneric_Name", b =>
                {
                    b.HasOne("medica1.Models.Generic_Name", null)
                        .WithMany()
                        .HasForeignKey("Combinationgeneric_NamesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("medica1.Models.Combination", null)
                        .WithMany()
                        .HasForeignKey("GenericcombinationsMedicine_Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CombinationMedicine_Type", b =>
                {
                    b.HasOne("medica1.Models.Medicine_Type", null)
                        .WithMany()
                        .HasForeignKey("CombinationMedicine_TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("medica1.Models.Combination", null)
                        .WithMany()
                        .HasForeignKey("Medicine_TypeCombinationMedicine_Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generic_NameMedicine_Name", b =>
                {
                    b.HasOne("medica1.Models.Medicine_Name", null)
                        .WithMany()
                        .HasForeignKey("Genetic_Namemedicine_NamesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("medica1.Models.Generic_Name", null)
                        .WithMany()
                        .HasForeignKey("Medicine_Namegeneric_NamesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
