// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisApplication.Context;

#nullable disable

namespace MisApplication.Migrations
{
    [DbContext(typeof(MVCContex))]
    [Migration("20220619183712_Independent")]
    partial class Independent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MisApplication.Models.mis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Admission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DandC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dialysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discharge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dressing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InjectionPush")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NVD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nebulizer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFquentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFvalue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Physiotherapy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surgery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xray")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mis");
                });
#pragma warning restore 612, 618
        }
    }
}
